version: '3.0'

services:
  php-fpm:
    build: .dockerfiles
    restart: always
    container_name: php
    volumes:
      - ./.dockerfiles/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.dockerfiles/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/app
    working_dir: /app
    depends_on:
      - composer

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5436:5432
    volumes:
      - ./.dockerfiles/postgres/:/docker-entrypoint-initdb.d/

  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./.dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
    - 8086:80
    restart: always
    depends_on:
      - php-fpm
      - database

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog-auth
    restart: always
    env_file:
      - .env
    ports:
      - 1026:1025
      - 8026:8025

  composer:
    image: composer
    container_name: composer
    volumes:
      - ./:/app
    command: composer install

  rabbit:
    container_name: ${RABBITMQ_HOST}
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ./.data/rabbitmq/:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  consumer:
    build: .dockerfiles
    restart: always
    container_name: consumer
    volumes:
      - .:/app
      - ./.dockerfiles/php/supervisord.tmpl.conf:/etc/supervisor/conf.d/supervisord.conf
    working_dir: /app
    depends_on:
      - php-fpm
      - mailhog
    entrypoint:
      - bash
      - -c
      - /usr/bin/supervisord -n